matrix:
  include:
    -os: linux
    language: c
    addons:
      artifacts: true
      apt:
        packages:
        - libsndfile1-dev
    compiler:
      - gcc
      - clang
    script:
      - autoreconf -i
      - ./configure
      - make distcheck

